version: "3.5"

services:
    web:
        container_name: line-it-news-web
        image: bref/fpm-dev-gateway
        ports:
            - '8010:80'
        volumes:
            - .:/var/task:ro
            - ./storage:/var/task/storage
        depends_on:
            - php
        environment:
            HANDLER: public/index.php
            DOCUMENT_ROOT: public

    php:
        container_name: line-it-news-php
        image: bref/php-74-fpm-dev
        volumes:
            - .:/var/task:ro
            - ./storage:/var/task/storage